stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.12-dind

before_script:
  - apt-get update -qy
  - apt-get install -y docker-compose

build:
  stage: build
  image: ubuntu:latest
  script:
    - apt-get update -qy
    - apt-get install -y docker-compose
    - docker-compose up -d --build  # Сборка и запуск контейнеров
    - docker-compose ps  # Вывод информации о контейнерах
    - docker-compose logs  # Просмотр логов контейнеров
